import { z, defineCollection } from 'astro:content';
import { glob } from 'astro/loaders';

// ✅ New: Commercial Kitchens collection
const commercialKitchensCollection = defineCollection({
  loader: glob({ pattern: '**/*.{md,mdx}', base: './src/content/commercial-kitchens' }),
  schema: ({ image }) => z.object({
    title: z.string(),
    metaTitle: z.string().optional(),
    slug: z.string().optional(),
    category: z.string().optional(),
    metaDescription: z.string().optional(),
    heroTitle: z.string().optional(),
    heroSubtitle: z.string().optional(),
    image: z.string().optional(),
    imageAlt: z.string().optional(),
    description: z.string().optional(),
    publish: z.string().optional(),
    order: z.number().optional(),
    section1Image: z.string().optional(),
    section1Alt: z.string().optional(),
    section1Title: z.string().optional(),
    section1Description: z.string().optional(),
    section2Image: z.string().optional(),
    section2Alt: z.string().optional(),
    section2Title: z.string().optional(),
    section2Description: z.string().optional(),
    section3Image: z.string().optional(),
    section3Alt: z.string().optional(),
    section3Title: z.string().optional(),
    section3Description: z.string().optional(),
    section4Image: z.string().optional(),
    section4Alt: z.string().optional(),
    section4Title: z.string().optional(),
    section4Description: z.string().optional(),
    section5Image: z.string().optional(),
    section5Alt: z.string().optional(),
    section5Title: z.string().optional(),
    section5Description: z.string().optional(),
    section6Image: z.string().optional(),
    section6Alt: z.string().optional(),
    section6Title: z.string().optional(),
    section6Description: z.string().optional(),
    section7Image: z.string().optional(),
    section7Alt: z.string().optional(),
    section7Title: z.string().optional(),
    section7Description: z.string().optional(),
    section8Image: z.string().optional(),
    section8Alt: z.string().optional(),
    section8Title: z.string().optional(),
    section8Description: z.string().optional(),
    section9Image: z.string().optional(),
    section9Alt: z.string().optional(),
    section9Title: z.string().optional(),
    section9Description: z.string().optional(),
    section10Image: z.string().optional(),
    section10Alt: z.string().optional(),
    section10Title: z.string().optional(),
    section10Description: z.string().optional(),
    ourProcessSubtitle: z.string().optional(),
    ourProcessTitle: z.string().optional(),
    ourProcessDescription: z.string().optional(),
    cta1Icon: z.string().optional(),
    cta1Title: z.string().optional(),
    cta1Description: z.string().optional(),
    cta2Icon: z.string().optional(),
    cta2Title: z.string().optional(),
    cta2Description: z.string().optional(),
    cta3Icon: z.string().optional(),
    cta3Title: z.string().optional(),
    cta3Description: z.string().optional(),
    footNote: z.string().optional(),
  }),
});

// ✅ New: Services collection
const servicesCollection = defineCollection({
  loader: glob({ pattern: '**/*.{md,mdx}', base: './src/content/services' }),
  schema: z.object({
    title: z.string(),
    metaTitle: z.string().optional(),
    slug: z.string().optional(),
    category: z.string().optional(),
    metaDescription: z.string().optional(),
    heroTitle: z.string().optional(),
    heroSubtitle: z.string().optional(),
    feature1Image: z.string().optional(),
    feature1Title: z.string().optional(),
    feature1Description: z.string().optional(),
    feature2Image: z.string().optional(),
    feature2Title: z.string().optional(),
    feature2Description: z.string().optional(),
    feature3Image: z.string().optional(),
    feature3Title: z.string().optional(),
    feature3Description: z.string().optional(),
    ourProcessSubtitle: z.string().optional(),
    ourProcessTitle: z.string().optional(),
    ourProcessDescription: z.string().optional(),
    cta1Icon: z.string().optional(),
    cta1Title: z.string().optional(),
    cta1Description: z.string().optional(),
    cta2Icon: z.string().optional(),
    cta2Title: z.string().optional(),
    cta2Description: z.string().optional(),
    cta3Icon: z.string().optional(),
    cta3Title: z.string().optional(),
    cta3Description: z.string().optional(),
    footNote: z.string().optional(),
  }),
});

// ✅ New: Industrial Bakeries collection
const industrialBakeriesCollection = defineCollection({
  loader: glob({ pattern: '**/*.{md,mdx}', base: './src/content/industrial-bakeries' }),
  schema: ({ image }) => z.object({
    title: z.string(),
    metaTitle: z.string().optional(),
    slug: z.string().optional(),
    category: z.string().optional(),
    metaDescription: z.string().optional(),
    heroTitle: z.string().optional(),
    heroSubtitle: z.string().optional(),
    image: z.string().optional(),
    imageAlt: z.string().optional(),
    description: z.string().optional(),
    publish: z.string().optional(),
    order: z.number().optional(),
    section1Image: z.string().optional(),
    section1Alt: z.string().optional(),
    section1Title: z.string().optional(),
    section1Description: z.string().optional(),
    section2Image: z.string().optional(),
    section2Alt: z.string().optional(),
    section2Title: z.string().optional(),
    section2Description: z.string().optional(),
    section3Image: z.string().optional(),
    section3Alt: z.string().optional(),
    section3Title: z.string().optional(),
    section3Description: z.string().optional(),
    section4Image: z.string().optional(),
    section4Alt: z.string().optional(),
    section4Title: z.string().optional(),
    section4Description: z.string().optional(),
    section5Image: z.string().optional(),
    section5Alt: z.string().optional(),
    section5Title: z.string().optional(),
    section5Description: z.string().optional(),
    section6Image: z.string().optional(),
    section6Alt: z.string().optional(),
    section6Title: z.string().optional(),
    section6Description: z.string().optional(),
    section7Image: z.string().optional(),
    section7Alt: z.string().optional(),
    section7Title: z.string().optional(),
    section7Description: z.string().optional(),
    section8Image: z.string().optional(),
    section8Alt: z.string().optional(),
    section8Title: z.string().optional(),
    section8Description: z.string().optional(),
    section9Image: z.string().optional(),
    section9Alt: z.string().optional(),
    section9Title: z.string().optional(),
    section9Description: z.string().optional(),
    section10Image: z.string().optional(),
    section10Alt: z.string().optional(),
    section10Title: z.string().optional(),
    section10Description: z.string().optional(),
    ourProcessSubtitle: z.string().optional(),
    ourProcessTitle: z.string().optional(),
    ourProcessDescription: z.string().optional(),
    cta1Icon: z.string().optional(),
    cta1Title: z.string().optional(),
    cta1Description: z.string().optional(),
    cta2Icon: z.string().optional(),
    cta2Title: z.string().optional(),
    cta2Description: z.string().optional(),
    cta3Icon: z.string().optional(),
    cta3Title: z.string().optional(),
    cta3Description: z.string().optional(),
    footNote: z.string().optional(),
  }),
});

const blogCollection = defineCollection({
  loader: glob({ pattern: '**/*.{md,mdx}', base: './src/content/blog' }),
  schema: ({ image }) => z.object({
    title: z.string(),
    metaTitle: z.string().optional(),
    slug: z.string().optional(),
    date: z.string().optional(),
    metaDescription: z.string().optional(),
    imageFeatured: z.string().optional(),
    imageAlt: z.string().optional(),
    categories: z.string().optional(),
    tags: z.string().optional(),
    status: z.string().optional(),
    authorId: z.string().optional(),
    authorName: z.string().optional(),
  }),
});

const productsCollection = defineCollection({
  loader: glob({ pattern: '**/*.{md,mdx}', base: './src/content/products' }),
  schema: ({ image }) => z.object({
    title: z.string(),
    metaTitle: z.string().optional(),
    slug: z.string().optional(),
    metaDescription: z.string().optional(),
    image: z.string().optional(), // Using string for mapping to assets later
    imageAlt: z.string().optional(),
    category: z.string().optional(),
    description: z.string().optional(),
    material: z.string().optional(),
    options: z.string().optional(),
    Material: z.string().optional(),
    Options: z.string().optional(),
    Serial: z.string().optional(),
    serial: z.string().optional(),
    "Category Description": z.string().optional(),
  }).passthrough(),
});

const projectsCollection = defineCollection({
  loader: glob({ pattern: '**/*.{md,mdx}', base: './src/content/projects' }),
  schema: ({ image }) => z.object({
    title: z.string(),
    metaTitle: z.string().optional(),
    slug: z.string().optional(),
    metaDescription: z.string().optional(),
    location: z.string().optional(),
    description: z.string().optional(),
    image: image().optional(),
    imageAlt: z.string().optional(),
    category: z.string().optional(),
    feature1Image: image().optional(),
    feature2Image: image().optional(),
    feature3Image: image().optional(),
  }).passthrough(),
});

export const collections = {
  commercialKitchens: commercialKitchensCollection, // ✅ register kiya
  services: servicesCollection,
  industrialBakeries: industrialBakeriesCollection,
  blog: blogCollection,
  products: productsCollection,
  projects: projectsCollection,
};