import { z, defineCollection } from 'astro:content';
import { glob } from 'astro/loaders';

const fragnanceNotesCollection = defineCollection({
  loader: glob({ pattern: '**/*.{md,mdx}', base: './src/content/fragnance-notes' }),
  schema: z.object({
    title: z.string(),
    group: z.string().optional(),
    image: z.string().optional(),
    pageTitle: z.string().optional(),
    metaDescription: z.string().optional(),
    odorProfile: z.string().optional(),
  }),
});


const perfumeCollection = defineCollection({
  loader: glob({ pattern: '**/*.{md,mdx}', base: './src/content/perfume' }),
  schema: z.object({
    perfumeName: z.string(),
    slug: z.string().optional(),
    year: z.string().optional(),
    use: z.string().optional(),
    productPageUrl: z.string().optional(),
    imageUrl: z.string().optional(),
    collectionName: z.string().optional(),
    brandName: z.string().optional(),
    topNotes: z.string().optional(),
    middleNotes: z.string().optional(),
    baseNotes: z.string().optional(),
    pros: z.string().optional(),
    cons: z.string().optional(),
    openingSentence: z.string().optional(),
  }),
});

// ✅ New: Commercial Kitchens collection
const commercialKitchensCollection = defineCollection({
  loader: glob({ pattern: '**/*.{md,mdx}', base: './src/content/commercial-kitchens' }),
  schema: ({ image }) => z.object({
    title: z.string(),
    metaTitle: z.string().optional(),
    slug: z.string().optional(),
    category: z.string().optional(),
    metaDescription: z.string().optional(),
    heroTitle: z.string().optional(),
    heroSubtitle: z.string().optional(),
    feature1Image: image().optional(),
    feature1Alt: z.string().optional(),
    feature1Title: z.string().optional(),
    feature1Description: z.string().optional(),
    feature2Image: image().optional(),
    feature2Alt: z.string().optional(),
    feature2Title: z.string().optional(),
    feature2Description: z.string().optional(),
    feature3Image: image().optional(),
    feature3Alt: z.string().optional(),
    feature3Title: z.string().optional(),
    feature3Description: z.string().optional(),
    ourProcessSubtitle: z.string().optional(),
    ourProcessTitle: z.string().optional(),
    ourProcessDescription: z.string().optional(),
    cta1Icon: z.string().optional(),
    cta1Title: z.string().optional(),
    cta1Description: z.string().optional(),
    cta2Icon: z.string().optional(),
    cta2Title: z.string().optional(),
    cta2Description: z.string().optional(),
    cta3Icon: z.string().optional(),
    cta3Title: z.string().optional(),
    cta3Description: z.string().optional(),
    footNote: z.string().optional(),
  }),
});

// ✅ New: Services collection
const servicesCollection = defineCollection({
  loader: glob({ pattern: '**/*.{md,mdx}', base: './src/content/services' }),
  schema: z.object({
    title: z.string(),
    metaTitle: z.string().optional(),
    slug: z.string().optional(),
    category: z.string().optional(),
    metaDescription: z.string().optional(),
    heroTitle: z.string().optional(),
    heroSubtitle: z.string().optional(),
    feature1Image: z.string().optional(),
    feature1Title: z.string().optional(),
    feature1Description: z.string().optional(),
    feature2Image: z.string().optional(),
    feature2Title: z.string().optional(),
    feature2Description: z.string().optional(),
    feature3Image: z.string().optional(),
    feature3Title: z.string().optional(),
    feature3Description: z.string().optional(),
    ourProcessSubtitle: z.string().optional(),
    ourProcessTitle: z.string().optional(),
    ourProcessDescription: z.string().optional(),
    cta1Icon: z.string().optional(),
    cta1Title: z.string().optional(),
    cta1Description: z.string().optional(),
    cta2Icon: z.string().optional(),
    cta2Title: z.string().optional(),
    cta2Description: z.string().optional(),
    cta3Icon: z.string().optional(),
    cta3Title: z.string().optional(),
    cta3Description: z.string().optional(),
    footNote: z.string().optional(),
  }),
});

// ✅ New: Industrial Bakeries collection
const industrialBakeriesCollection = defineCollection({
  loader: glob({ pattern: '**/*.{md,mdx}', base: './src/content/industrial-bakeries' }),
  schema: ({ image }) => z.object({
    title: z.string(),
    metaTitle: z.string().optional(),
    slug: z.string().optional(),
    category: z.string().optional(),
    metaDescription: z.string().optional(),
    heroTitle: z.string().optional(),
    heroSubtitle: z.string().optional(),
    feature1Image: image().optional(),
    feature1Alt: z.string().optional(),
    feature1Title: z.string().optional(),
    feature1Description: z.string().optional(),
    feature2Image: image().optional(),
    feature2Alt: z.string().optional(),
    feature2Title: z.string().optional(),
    feature2Description: z.string().optional(),
    feature3Image: image().optional(),
    feature3Alt: z.string().optional(),
    feature3Title: z.string().optional(),
    feature3Description: z.string().optional(),
    ourProcessSubtitle: z.string().optional(),
    ourProcessTitle: z.string().optional(),
    ourProcessDescription: z.string().optional(),
    cta1Icon: z.string().optional(),
    cta1Title: z.string().optional(),
    cta1Description: z.string().optional(),
    cta2Icon: z.string().optional(),
    cta2Title: z.string().optional(),
    cta2Description: z.string().optional(),
    cta3Icon: z.string().optional(),
    cta3Title: z.string().optional(),
    cta3Description: z.string().optional(),
    footNote: z.string().optional(),
  }),
});

const blogCollection = defineCollection({
  loader: glob({ pattern: '**/*.{md,mdx}', base: './src/content/blog' }),
  schema: ({ image }) => z.object({
    title: z.string(),
    metaTitle: z.string().optional(),
    slug: z.string().optional(),
    date: z.string().optional(),
    metaDescription: z.string().optional(),
    imageFeatured: z.string().optional(),
    imageAlt: z.string().optional(),
    categories: z.string().optional(),
    tags: z.string().optional(),
    status: z.string().optional(),
    authorId: z.string().optional(),
    authorName: z.string().optional(),
  }),
});

export const collections = {
  fragnanceNotes: fragnanceNotesCollection,
  perfume: perfumeCollection,
  commercialKitchens: commercialKitchensCollection, // ✅ register kiya
  services: servicesCollection,
  industrialBakeries: industrialBakeriesCollection,
  blog: blogCollection,
};