import { z, defineCollection } from 'astro:content';
import { glob } from 'astro/loaders';

// ✅ New: Commercial Kitchens collection
const commercialKitchensCollection = defineCollection({
  loader: glob({ pattern: '**/*.{md,mdx}', base: './src/content/commercial-kitchens' }),
  schema: ({ image }) => z.object({
    title: z.string(),
    metaTitle: z.string().optional(),
    slug: z.string().optional(),
    category: z.string().optional(),
    metaDescription: z.string().optional(),
    heroTitle: z.string().optional(),
    heroSubtitle: z.string().optional(),
    image: z.string().optional(),
    imageAlt: z.string().optional(),
    description: z.string().optional(),
    publish: z.string().optional(),
    order: z.number().optional(),
    feature1Image: z.string().optional(),
    feature1Alt: z.string().optional(),
    feature1Title: z.string().optional(),
    feature1Description: z.string().optional(),
    feature2Image: z.string().optional(),
    feature2Alt: z.string().optional(),
    feature2Title: z.string().optional(),
    feature2Description: z.string().optional(),
    feature3Image: z.string().optional(),
    feature3Alt: z.string().optional(),
    feature3Title: z.string().optional(),
    feature3Description: z.string().optional(),
    feature4Image: z.string().optional(),
    feature4Alt: z.string().optional(),
    feature4Title: z.string().optional(),
    feature4Description: z.string().optional(),
    feature5Image: z.string().optional(),
    feature5Alt: z.string().optional(),
    feature5Title: z.string().optional(),
    feature5Description: z.string().optional(),
    feature6Image: z.string().optional(),
    feature6Alt: z.string().optional(),
    feature6Title: z.string().optional(),
    feature6Description: z.string().optional(),
    feature7Image: z.string().optional(),
    feature7Alt: z.string().optional(),
    feature7Title: z.string().optional(),
    feature7Description: z.string().optional(),
    feature8Image: z.string().optional(),
    feature8Alt: z.string().optional(),
    feature8Title: z.string().optional(),
    feature8Description: z.string().optional(),
    feature9Image: z.string().optional(),
    feature9Alt: z.string().optional(),
    feature9Title: z.string().optional(),
    feature9Description: z.string().optional(),
    feature10Image: z.string().optional(),
    feature10Alt: z.string().optional(),
    feature10Title: z.string().optional(),
    feature10Description: z.string().optional(),
    ourProcessSubtitle: z.string().optional(),
    ourProcessTitle: z.string().optional(),
    ourProcessDescription: z.string().optional(),
    cta1Icon: z.string().optional(),
    cta1Title: z.string().optional(),
    cta1Description: z.string().optional(),
    cta2Icon: z.string().optional(),
    cta2Title: z.string().optional(),
    cta2Description: z.string().optional(),
    cta3Icon: z.string().optional(),
    cta3Title: z.string().optional(),
    cta3Description: z.string().optional(),
    footNote: z.string().optional(),
  }).passthrough(),
});

// ✅ New: Services collection
const servicesCollection = defineCollection({
  loader: glob({ pattern: '**/*.{md,mdx}', base: './src/content/services' }),
  schema: z.object({
    title: z.string(),
    metaTitle: z.string().optional(),
    slug: z.string().optional(),
    image: z.string().optional(),
    imageAlt: z.string().optional(),
    category: z.string().optional(),
    metaDescription: z.string().optional(),
    heroTitle: z.string().optional(),
    heroSubtitle: z.string().optional(),
    feature1Image: z.string().optional(),
    feature1Alt: z.string().optional(),
    feature1Title: z.string().optional(),
    feature1Description: z.string().optional(),
    feature2Image: z.string().optional(),
    feature2Alt: z.string().optional(),
    feature2Title: z.string().optional(),
    feature2Description: z.string().optional(),
    feature3Image: z.string().optional(),
    feature3Alt: z.string().optional(),
    feature3Title: z.string().optional(),
    feature3Description: z.string().optional(),
    feature4Image: z.string().optional(),
    feature4Alt: z.string().optional(),
    feature4Title: z.string().optional(),
    feature4Description: z.string().optional(),
    feature5Image: z.string().optional(),
    feature5Alt: z.string().optional(),
    feature5Title: z.string().optional(),
    feature5Description: z.string().optional(),
    feature6Image: z.string().optional(),
    feature6Alt: z.string().optional(),
    feature6Title: z.string().optional(),
    feature6Description: z.string().optional(),
    feature7Image: z.string().optional(),
    feature7Alt: z.string().optional(),
    feature7Title: z.string().optional(),
    feature7Description: z.string().optional(),
    feature8Image: z.string().optional(),
    feature8Alt: z.string().optional(),
    feature8Title: z.string().optional(),
    feature8Description: z.string().optional(),
    feature9Image: z.string().optional(),
    feature9Alt: z.string().optional(),
    feature9Title: z.string().optional(),
    feature9Description: z.string().optional(),
    feature10Image: z.string().optional(),
    feature10Alt: z.string().optional(),
    feature10Title: z.string().optional(),
    feature10Description: z.string().optional(),
    ourProcessSubtitle: z.string().optional(),
    ourProcessTitle: z.string().optional(),
    ourProcessDescription: z.string().optional(),
    cta1Icon: z.string().optional(),
    cta1Title: z.string().optional(),
    cta1Description: z.string().optional(),
    cta2Icon: z.string().optional(),
    cta2Title: z.string().optional(),
    cta2Description: z.string().optional(),
    cta3Icon: z.string().optional(),
    cta3Title: z.string().optional(),
    cta3Description: z.string().optional(),
    footNote: z.string().optional(),
  }).passthrough(),
});

// ✅ New: Industrial Bakeries collection
const industrialBakeriesCollection = defineCollection({
  loader: glob({ pattern: '**/*.{md,mdx}', base: './src/content/industrial-bakeries' }),
  schema: ({ image }) => z.object({
    title: z.string(),
    metaTitle: z.string().optional(),
    slug: z.string().optional(),
    category: z.string().optional(),
    metaDescription: z.string().optional(),
    heroTitle: z.string().optional(),
    heroSubtitle: z.string().optional(),
    image: z.string().optional(),
    imageAlt: z.string().optional(),
    description: z.string().optional(),
    publish: z.string().optional(),
    order: z.number().optional(),
    feature1Image: z.string().optional(),
    feature1Alt: z.string().optional(),
    feature1Title: z.string().optional(),
    feature1Description: z.string().optional(),
    feature2Image: z.string().optional(),
    feature2Alt: z.string().optional(),
    feature2Title: z.string().optional(),
    feature2Description: z.string().optional(),
    feature3Image: z.string().optional(),
    feature3Alt: z.string().optional(),
    feature3Title: z.string().optional(),
    feature3Description: z.string().optional(),
    feature4Image: z.string().optional(),
    feature4Alt: z.string().optional(),
    feature4Title: z.string().optional(),
    feature4Description: z.string().optional(),
    feature5Image: z.string().optional(),
    feature5Alt: z.string().optional(),
    feature5Title: z.string().optional(),
    feature5Description: z.string().optional(),
    feature6Image: z.string().optional(),
    feature6Alt: z.string().optional(),
    feature6Title: z.string().optional(),
    feature6Description: z.string().optional(),
    feature7Image: z.string().optional(),
    feature7Alt: z.string().optional(),
    feature7Title: z.string().optional(),
    feature7Description: z.string().optional(),
    feature8Image: z.string().optional(),
    feature8Alt: z.string().optional(),
    feature8Title: z.string().optional(),
    feature8Description: z.string().optional(),
    feature9Image: z.string().optional(),
    feature9Alt: z.string().optional(),
    feature9Title: z.string().optional(),
    feature9Description: z.string().optional(),
    feature10Image: z.string().optional(),
    feature10Alt: z.string().optional(),
    feature10Title: z.string().optional(),
    feature10Description: z.string().optional(),
    ourProcessSubtitle: z.string().optional(),
    ourProcessTitle: z.string().optional(),
    ourProcessDescription: z.string().optional(),
    cta1Icon: z.string().optional(),
    cta1Title: z.string().optional(),
    cta1Description: z.string().optional(),
    cta2Icon: z.string().optional(),
    cta2Title: z.string().optional(),
    cta2Description: z.string().optional(),
    cta3Icon: z.string().optional(),
    cta3Title: z.string().optional(),
    cta3Description: z.string().optional(),
    footNote: z.string().optional(),
  }).passthrough(),
});

const blogCollection = defineCollection({
  loader: glob({ pattern: '**/*.{md,mdx}', base: './src/content/blog' }),
  schema: ({ image }) => z.object({
    title: z.string(),
    metaTitle: z.string().optional(),
    slug: z.string().optional(),
    date: z.string().optional(),
    metaDescription: z.string().optional(),
    imageFeatured: z.string().optional(),
    imageAlt: z.string().optional(),
    categories: z.string().optional(),
    tags: z.string().optional(),
    status: z.string().optional(),
    authorId: z.string().optional(),
    authorName: z.string().optional(),
  }),
});

const productsCollection = defineCollection({
  loader: glob({ pattern: '**/*.{md,mdx}', base: './src/content/products' }),
  schema: ({ image }) => z.object({
    title: z.string(),
    metaTitle: z.string().optional(),
    slug: z.string().optional(),
    metaDescription: z.string().optional(),
    image: z.string().optional(), // Using string for mapping to assets later
    imageAlt: z.string().optional(),
    category: z.string().optional(),
    description: z.string().optional(),
    material: z.string().optional(),
    options: z.string().optional(),
    Material: z.string().optional(),
    Options: z.string().optional(),
    Serial: z.string().optional(),
    serial: z.string().optional(),
    "Category Description": z.string().optional(),
  }).passthrough(),
});

const projectsCollection = defineCollection({
  loader: glob({ pattern: '**/*.{md,mdx}', base: './src/content/projects' }),
  schema: ({ image }) => z.object({
    title: z.string(),
    metaTitle: z.string().optional(),
    slug: z.string().optional(),
    metaDescription: z.string().optional(),
    location: z.string().optional(),
    description: z.string().optional(),
    image: image().optional(),
    imageAlt: z.string().optional(),
    category: z.string().optional(),
    feature1Image: image().optional(),
    feature2Image: image().optional(),
    feature3Image: image().optional(),
  }).passthrough(),
});

export const collections = {
  commercialKitchens: commercialKitchensCollection, // ✅ register kiya
  services: servicesCollection,
  industrialBakeries: industrialBakeriesCollection,
  blog: blogCollection,
  products: productsCollection,
  projects: projectsCollection,
};